package se.kth.iv1350.pos.adaptation;

/**
 * Demonstrates the use of inheritance and composition
 * to adapt the behavior of the {@link java.util.Random} class.
 * <p>
 * It creates instances of {@link InheritedRandom} and {@link ComposedRandom}
 * and prints out random integers generated by each.
 */
public class AdaptationDemo {
    /**
     * The main entry point of the program.
     * Creates objects of InheritedRandom and ComposedRandom classes
     * and prints several random integers generated by each.
     * @param args Command line arguments (not used).
     */
    public static void main(String[] args) {
        InheritedRandom inheritedRandom = new InheritedRandom();
        ComposedRandom composedRandom = new ComposedRandom();

        System.out.println("Testing InheritedRandom:");
        for (int i = 0; i < 5; i++) {
            System.out.println(inheritedRandom.nextInt());
        }

        System.out.println("\nTesting ComposedRandom:");
        for (int i = 0; i < 5; i++) {
            System.out.println(composedRandom.nextInt());
        }
    }
}
